#ifndef UAVCAN_NODE_ID_H
#define UAVCAN_NODE_ID_H

//UAVCAN node ID definitions
#define UAVCAN_NODE_ID_TORPEDO_BOARD 11
#define UAVCAN_NODE_ID_INTERNAL_SENSOR_BOARD 12
#define UAVCAN_NODE_ID_BATTERY_MONITORING_BOARD 13

#endif